underwater detection based on sky object
llde/TESReloaded10 pull request #77
Opened 2022-12-10 15:14 UTC by mchaptel

use the sky TES object flags to detect whether to activate underwater

2022-12-14 09:58 UTC, llde requested changes
Replicate the IsUnderwater to Oblivion frameework too,

2022-12-14 09:58 UTC, llde commented on TESReloaded/Framework/NewVegas/Game.h
> +	enum Flags : unsigned __int32
Use UInt32

2022-12-14 14:23 UTC, llde commented on TESReloaded/Framework/NewVegas/Game.h
> +	enum Flags : unsigned __int32
> can you check that it is in fact supported? I don't have oblivion to test it. I'll make the changes and you can test them if you prefer

2022-12-14 21:16 UTC, llde commented
change unsigned __int32 to UInt32 @mchaptel and I commit

2022-12-15 19:08 UTC, mchaptel commented
I've made the change and also added the relevant flags for oblivion. I figured it would be better to fix it if the flag is wrong instead of having it break because the function is called without existing?

I've also commented out the code that makes the reflection fix happen only when the water shader is active. Let me know if I need to remove it

2022-12-15 20:47 UTC, llde approved these changes

2022-12-15 20:48 UTC, merged